language: node_js
node_js:
  - '8'
  - '7'
  - '6'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - g++-4.9
install: npm install
jobs:
  include:
    - stage: test
      script: npm test
    - stage: deploy
      script: bash ./travis-deploy.sh
cache:
  directories:
    - node_modules
env:
  - CXX=g++-4.9
sudo: false
